/** Code generated by EriLex */
package databook.edsl.googql;
public class actionHead<Kappa,Sigma,__t,__E> {
	F<DactionHead<__t,__E>,Sigma> b;
	F<Sigma,Kappa> k;
	public actionHead(
		final F<DactionHead<__t,__E>,Sigma> b, 
		final F<Sigma,Kappa> k) {
		this.b=b;
		this.k=k;
	}
	public action<Kappa,Sigma,__t,__E> node(
		final java.net.URI i1) {
		return new F<F<Daction<__t,__E>,Sigma>,action<Kappa,Sigma,__t,__E>>() {
			public action<Kappa,Sigma,__t,__E> APP(final F<Daction<__t,__E>,Sigma> b1) {
				return new action(
					b1, 
					k);
			}
		}.APP(new F<Daction<__t,__E>,Sigma>() {
			public Sigma APP(final Daction<__t,__E> t1) {
				return b.APP(new DactionHeadDnode(
					i1, 
					t1));
			}
		});
	}
}
