/** Code generated by EriLex */
package databook.edsl.googql;
public class action<Kappa,Sigma,__t,__E> {
	F<Daction<__t,__E>,Sigma> b;
	F<Sigma,Kappa> k;
	public action(
		final F<Daction<__t,__E>,Sigma> b, 
		final F<Sigma,Kappa> k) {
		this.b=b;
		this.k=k;
	}
	public action<Kappa,Sigma,__t,__E> time() {
		return new F<F<Daction<__t,__E>,Sigma>,action<Kappa,Sigma,__t,__E>>() {
			public action<Kappa,Sigma,__t,__E> APP(final F<Daction<__t,__E>,Sigma> b1) {
				return new action(
					b1, 
					k);
			}
		}.APP(new F<Daction<__t,__E>,Sigma>() {
			public Sigma APP(final Daction<__t,__E> t1) {
				return b.APP(new DactionDtime(
					t1));
			}
		});
	}
	public action<Kappa,Sigma,__t,__E> uri() {
		return new F<F<Daction<__t,__E>,Sigma>,action<Kappa,Sigma,__t,__E>>() {
			public action<Kappa,Sigma,__t,__E> APP(final F<Daction<__t,__E>,Sigma> b1) {
				return new action(
					b1, 
					k);
			}
		}.APP(new F<Daction<__t,__E>,Sigma>() {
			public Sigma APP(final Daction<__t,__E> t1) {
				return b.APP(new Dactionuri(
					t1));
			}
		});
	}
	public action<Kappa,Sigma,__t,__E> sel() {
		return new F<F<Daction<__t,__E>,Sigma>,action<Kappa,Sigma,__t,__E>>() {
			public action<Kappa,Sigma,__t,__E> APP(final F<Daction<__t,__E>,Sigma> b1) {
				return new action(
					b1, 
					k);
			}
		}.APP(new F<Daction<__t,__E>,Sigma>() {
			public Sigma APP(final Daction<__t,__E> t1) {
				return b.APP(new DactionDsel(
					t1));
			}
		});
	}
	public action<Kappa,Sigma,__t,__E> follow(
		final java.lang.String i1) {
		return new F<F<Daction<__t,__E>,Sigma>,action<Kappa,Sigma,__t,__E>>() {
			public action<Kappa,Sigma,__t,__E> APP(final F<Daction<__t,__E>,Sigma> b1) {
				return new action(
					b1, 
					k);
			}
		}.APP(new F<Daction<__t,__E>,Sigma>() {
			public Sigma APP(final Daction<__t,__E> t1) {
				return b.APP(new DactionDfollow(
					i1, 
					t1));
			}
		});
	}
	public matchTail<Kappa,Sigma,__t,__E> match(
		final java.lang.String i1) {
		return new F<F<DmatchTail<__t,__E>,Sigma>,matchTail<Kappa,Sigma,__t,__E>>() {
			public matchTail<Kappa,Sigma,__t,__E> APP(final F<DmatchTail<__t,__E>,Sigma> b1) {
				return new matchTail(
					b1, 
					k);
			}
		}.APP(new F<DmatchTail<__t,__E>,Sigma>() {
			public Sigma APP(final DmatchTail<__t,__E> t1) {
				return b.APP(new DactionDmatch(
					i1, 
					t1));
			}
		});
	}
	public action<Kappa,Sigma,__t,__E> number() {
		return new F<F<Daction<__t,__E>,Sigma>,action<Kappa,Sigma,__t,__E>>() {
			public action<Kappa,Sigma,__t,__E> APP(final F<Daction<__t,__E>,Sigma> b1) {
				return new action(
					b1, 
					k);
			}
		}.APP(new F<Daction<__t,__E>,Sigma>() {
			public Sigma APP(final Daction<__t,__E> t1) {
				return b.APP(new DactionDnumber(
					t1));
			}
		});
	}
	public action<Kappa,Sigma,__t,__E> back() {
		return new F<F<Daction<__t,__E>,Sigma>,action<Kappa,Sigma,__t,__E>>() {
			public action<Kappa,Sigma,__t,__E> APP(final F<Daction<__t,__E>,Sigma> b1) {
				return new action(
					b1, 
					k);
			}
		}.APP(new F<Daction<__t,__E>,Sigma>() {
			public Sigma APP(final Daction<__t,__E> t1) {
				return b.APP(new DactionDback(
					t1));
			}
		});
	}
	public Kappa end() {
		return k.APP(b.APP(new DactionDend()));
	}
	public action<Kappa,Sigma,__t,__E> string() {
		return new F<F<Daction<__t,__E>,Sigma>,action<Kappa,Sigma,__t,__E>>() {
			public action<Kappa,Sigma,__t,__E> APP(final F<Daction<__t,__E>,Sigma> b1) {
				return new action(
					b1, 
					k);
			}
		}.APP(new F<Daction<__t,__E>,Sigma>() {
			public Sigma APP(final Daction<__t,__E> t1) {
				return b.APP(new DactionDstring(
					t1));
			}
		});
	}
	public action<Kappa,Sigma,__t,__E> integer() {
		return new F<F<Daction<__t,__E>,Sigma>,action<Kappa,Sigma,__t,__E>>() {
			public action<Kappa,Sigma,__t,__E> APP(final F<Daction<__t,__E>,Sigma> b1) {
				return new action(
					b1, 
					k);
			}
		}.APP(new F<Daction<__t,__E>,Sigma>() {
			public Sigma APP(final Daction<__t,__E> t1) {
				return b.APP(new DactionDinteger(
					t1));
			}
		});
	}
}
