/** Code generated by EriLex */
package databook.edsl.googql;
public class Constants {
	public static ID<databook.local.model.RDFServiceWrapper> DATABOOK_LOCAL_MODEL_RDFSERVICE=new ID<databook.local.model.RDFServiceWrapper>();
	public static ID<java.net.URI> JAVA_NET_URI=new ID<java.net.URI>();
	public static ID<java.lang.String> JAVA_LANG_STRING=new ID<java.lang.String>();
}
