/** Code generated by EriLex */
package databook.edsl.googql;
public class D__dbEqAxiom {
	public <E,S,T> F<D__db<S,E>,D__db<T,E>> appl(
		final F<S,T> eq) {
		return ((F<D__db<S,E>,D__db<T,E>>) eq) ;
	}
	public <t,S,T> F<D__db<t,T>,D__db<t,T>> appr(
		final F<S,T> eq) {
		return ((F<D__db<t,T>,D__db<t,T>>) eq) ;
	}
}
