/** Code generated by EriLex */
package databook.edsl.googql;
public abstract class D__db<t,Eta> extends erilex.data.generic.Tree<erilex.tree.ASTValueData> {
	public D__db(
		final erilex.tree.ASTValueData name, 
		final erilex.data.generic.Tree<erilex.tree.ASTValueData>... sub) {
		super(name, 
			sub);
	}
	public java.lang.Object run() {
		return this.accept(new Devaluate()
			, 
			new java.util.Stack<String>(), 
			null, 
			null);
	}
	public abstract java.lang.Object accept(
		final Visitor v, 
		final java.util.Stack<String> nodes, 
		final java.lang.Integer counter, 
		final java.util.List<String> selects);
}
