/** Code generated by EriLex */
package databook.edsl.googql;
public class DactionEqAxiom {
	public <E,S,T> F<Daction<S,E>,Daction<T,E>> appl(
		final F<S,T> eq) {
		return ((F<Daction<S,E>,Daction<T,E>>) eq) ;
	}
	public <t,S,T> F<Daction<t,T>,Daction<t,T>> appr(
		final F<S,T> eq) {
		return ((F<Daction<t,T>,Daction<t,T>>) eq) ;
	}
}
