/** Code generated by EriLex */
package databook.edsl.googql;
public class DactionDfollow<__t,__E> extends Daction<__t,__E> {
	java.lang.String i0;
	Daction<__t,__E> i1;
	public DactionDfollow(
		final java.lang.String i0, 
		final Daction<__t,__E> i1) {
		super(new erilex.tree.ASTValueData(
				"action", 
				"action")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"follow", 
					"follow")), 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"nat", 
					null, 
					i0)), 
			i1);
		this.i0=i0;
		this.i1=i1;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.util.Stack<String> nodes, 
		final java.lang.Integer counter, 
		final java.util.Map<String,Class> selects) {
		return v.visit(nodes, 
			counter, 
			selects, 
			this);
	}
	public static <__t,__E> DactionDfollow<__t,__E> follow(
		final java.lang.String i0, 
		final Daction<__t,__E> i1) {
		return new DactionDfollow<__t,__E>(
			i0, 
			i1);
	}
}
