/** Code generated by EriLex */
package databook.edsl.googql;
public class DactionHeadDnode<__t,__E> extends DactionHead<__t,__E> {
	java.net.URI i0;
	Daction<__t,__E> i1;
	public DactionHeadDnode(
		final java.net.URI i0, 
		final Daction<__t,__E> i1) {
		super(new erilex.tree.ASTValueData(
				"actionHead", 
				"actionHead")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"node", 
					"node")), 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"nat", 
					null, 
					i0)), 
			i1);
		this.i0=i0;
		this.i1=i1;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.util.Stack<String> nodes, 
		final java.lang.Integer counter, 
		final java.util.Map<String,Class> selects) {
		return v.visit(nodes, 
			counter, 
			selects, 
			this);
	}
	public static <__t,__E> DactionHeadDnode<__t,__E> node(
		final java.net.URI i0, 
		final Daction<__t,__E> i1) {
		return new DactionHeadDnode<__t,__E>(
			i0, 
			i1);
	}
}
