/** Code generated by EriLex */
package databook.edsl.googql;
public class DactionDend<__t,__E> extends Daction<__t,__E> {
	public DactionDend() {
		super(new erilex.tree.ASTValueData(
				"action", 
				"action")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"end", 
					"end")));
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.util.Stack<String> nodes, 
		final java.lang.Integer counter, 
		final java.util.Map<String,Class> selects) {
		return v.visit(nodes, 
			counter, 
			selects, 
			this);
	}
	public static <__t,__E> DactionDend<__t,__E> end() {
		return new DactionDend<__t,__E>();
	}
}
