/** Code generated by EriLex */
package databook.edsl.googql;
public class DmatchTailEqAxiom {
	public <E,S,T> F<DmatchTail<S,E>,DmatchTail<T,E>> appl(
		final F<S,T> eq) {
		return ((F<DmatchTail<S,E>,DmatchTail<T,E>>) eq) ;
	}
	public <t,S,T> F<DmatchTail<t,T>,DmatchTail<t,T>> appr(
		final F<S,T> eq) {
		return ((F<DmatchTail<t,T>,DmatchTail<t,T>>) eq) ;
	}
}
