/** Code generated by EriLex */
package databook.edsl.googql;
public class DqueryEqAxiom {
	public <E,S,T> F<Dquery<S,E>,Dquery<T,E>> appl(
		final F<S,T> eq) {
		return ((F<Dquery<S,E>,Dquery<T,E>>) eq) ;
	}
	public <t,S,T> F<Dquery<t,T>,Dquery<t,T>> appr(
		final F<S,T> eq) {
		return ((F<Dquery<t,T>,Dquery<t,T>>) eq) ;
	}
}
