/** Code generated by EriLex */
package databook.edsl.googql;
public class DqueryDuse<__t,__E> extends Dquery<__t,__E> {
	databook.local.model.RDFServiceWrapper i0;
	DactionHead<__t,__E> i1;
	public DqueryDuse(
		final databook.local.model.RDFServiceWrapper i0, 
		final DactionHead<__t,__E> i1) {
		super(new erilex.tree.ASTValueData(
				"query", 
				"query")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"use", 
					"use")), 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"nat", 
					null, 
					i0)), 
			i1);
		this.i0=i0;
		this.i1=i1;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.util.Stack<String> nodes, 
		final java.lang.Integer counter, 
		final java.util.Map<String,Class> selects) {
		return v.visit(nodes, 
			counter, 
			selects, 
			this);
	}
	public static <__t,__E> DqueryDuse<__t,__E> use(
		final databook.local.model.RDFServiceWrapper i0, 
		final DactionHead<__t,__E> i1) {
		return new DqueryDuse<__t,__E>(
			i0, 
			i1);
	}
}
