/** Code generated by EriLex */
package databook.edsl.googql;
public class query<Kappa,Sigma,__t,__E> {
	F<Dquery<__t,__E>,Sigma> b;
	F<Sigma,Kappa> k;
	public query(
		final F<Dquery<__t,__E>,Sigma> b, 
		final F<Sigma,Kappa> k) {
		this.b=b;
		this.k=k;
	}
	public actionHead<Kappa,Sigma,__t,__E> use(
		final databook.local.model.RDFServiceWrapper i1) {
		return new F<F<DactionHead<__t,__E>,Sigma>,actionHead<Kappa,Sigma,__t,__E>>() {
			public actionHead<Kappa,Sigma,__t,__E> APP(final F<DactionHead<__t,__E>,Sigma> b1) {
				return new actionHead(
					b1, 
					k);
			}
		}.APP(new F<DactionHead<__t,__E>,Sigma>() {
			public Sigma APP(final DactionHead<__t,__E> t1) {
				return b.APP(new DqueryDuse(
					i1, 
					t1));
			}
		});
	}
}
