/** Code generated by EriLex */
package databook.edsl.googql;
public class Utils {
	public static <T,__E> query<Dquery<T,__E>,Dquery<T,__E>,T,__E> query() {
		return new query<Dquery<T,__E>,Dquery<T,__E>,T,__E>(
			new UtilsST(), 
			new UtilsST());
	}
	public static <T,__E> query<Dquery<T,__E>,Dquery<T,__E>,T,__E> prog() {
		return query();
	}
	public static class UtilsST<T,__E> extends F<Dquery<T,__E>,Dquery<T,__E>> {
		public Dquery<T,__E> APP(
			final Dquery<T,__E> x) {
			return x;
		}
	}
}
