/** Code generated by EriLex */
package databook.edsl.map;
public class arrayTail<Kappa,Sigma,__t,__E> {
	F<DarrayTail<__t,__E>,Sigma> b;
	F<Sigma,Kappa> k;
	public arrayTail(
		final F<DarrayTail<__t,__E>,Sigma> b, 
		final F<Sigma,Kappa> k) {
		this.b=b;
		this.k=k;
	}
	public value<unit<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E>,F<Dunit<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>,__t,__E> attribute(
		final java.lang.String i1) {
		return new F<F<Dvalue<__t,__E>,F<Dunit<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>>,value<unit<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E>,F<Dunit<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>,__t,__E>>() {
			public value<unit<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E>,F<Dunit<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>,__t,__E> APP(final F<Dvalue<__t,__E>,F<Dunit<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>> b3) {
				return new value(
					b3, 
					new F<F<Dunit<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>,unit<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E>>() {
						public unit<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E> APP(final F<Dunit<__t,__E>,F<DarrayTail<__t,__E>,Sigma>> b2) {
							return new unit(
								b2, 
								new F<F<DarrayTail<__t,__E>,Sigma>,arrayTail<Kappa,Sigma,__t,__E>>() {
									public arrayTail<Kappa,Sigma,__t,__E> APP(final F<DarrayTail<__t,__E>,Sigma> b1) {
										return new arrayTail(
											b1, 
											k);
									}
								});
						}
					});
			}
		}.APP(new F<Dvalue<__t,__E>,F<Dunit<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>>() {
			public F<Dunit<__t,__E>,F<DarrayTail<__t,__E>,Sigma>> APP(final Dvalue<__t,__E> t1) {
				return new F<Dunit<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>() {
					public F<DarrayTail<__t,__E>,Sigma> APP(final Dunit<__t,__E> t2) {
						return new F<DarrayTail<__t,__E>,Sigma>() {
							public Sigma APP(final DarrayTail<__t,__E> t3) {
								return b.APP(new DarrayTailDattribute(
									i1, 
									t1, 
									t2, 
									t3));
							}
						};
					}
				};
			}
		});
	}
	public <t> arrayTail<Kappa,Sigma,__t,__E> elem(
		final t i1) {
		return new F<F<DarrayTail<__t,__E>,Sigma>,arrayTail<Kappa,Sigma,__t,__E>>() {
			public arrayTail<Kappa,Sigma,__t,__E> APP(final F<DarrayTail<__t,__E>,Sigma> b1) {
				return new arrayTail(
					b1, 
					k);
			}
		}.APP(new F<DarrayTail<__t,__E>,Sigma>() {
			public Sigma APP(final DarrayTail<__t,__E> t1) {
				return b.APP(new DarrayTailDelem(
					i1, 
					t1));
			}
		});
	}
	public map<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E> object() {
		return new F<F<Dmap<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>,map<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E>>() {
			public map<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E> APP(final F<Dmap<__t,__E>,F<DarrayTail<__t,__E>,Sigma>> b2) {
				return new map(
					b2, 
					new F<F<DarrayTail<__t,__E>,Sigma>,arrayTail<Kappa,Sigma,__t,__E>>() {
						public arrayTail<Kappa,Sigma,__t,__E> APP(final F<DarrayTail<__t,__E>,Sigma> b1) {
							return new arrayTail(
								b1, 
								k);
						}
					});
			}
		}.APP(new F<Dmap<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>() {
			public F<DarrayTail<__t,__E>,Sigma> APP(final Dmap<__t,__E> t1) {
				return new F<DarrayTail<__t,__E>,Sigma>() {
					public Sigma APP(final DarrayTail<__t,__E> t2) {
						return b.APP(new DarrayTailDobject(
							t1, 
							t2));
					}
				};
			}
		});
	}
	public map<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E> dataObject() {
		return new F<F<Dmap<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>,map<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E>>() {
			public map<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E> APP(final F<Dmap<__t,__E>,F<DarrayTail<__t,__E>,Sigma>> b2) {
				return new map(
					b2, 
					new F<F<DarrayTail<__t,__E>,Sigma>,arrayTail<Kappa,Sigma,__t,__E>>() {
						public arrayTail<Kappa,Sigma,__t,__E> APP(final F<DarrayTail<__t,__E>,Sigma> b1) {
							return new arrayTail(
								b1, 
								k);
						}
					});
			}
		}.APP(new F<Dmap<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>() {
			public F<DarrayTail<__t,__E>,Sigma> APP(final Dmap<__t,__E> t1) {
				return new F<DarrayTail<__t,__E>,Sigma>() {
					public Sigma APP(final DarrayTail<__t,__E> t2) {
						return b.APP(new DarrayTailDdataObject(
							t1, 
							t2));
					}
				};
			}
		});
	}
	public Kappa end() {
		return k.APP(b.APP(new DarrayTailDend()));
	}
	public map<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E> collection() {
		return new F<F<Dmap<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>,map<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E>>() {
			public map<arrayTail<Kappa,Sigma,__t,__E>,F<DarrayTail<__t,__E>,Sigma>,__t,__E> APP(final F<Dmap<__t,__E>,F<DarrayTail<__t,__E>,Sigma>> b2) {
				return new map(
					b2, 
					new F<F<DarrayTail<__t,__E>,Sigma>,arrayTail<Kappa,Sigma,__t,__E>>() {
						public arrayTail<Kappa,Sigma,__t,__E> APP(final F<DarrayTail<__t,__E>,Sigma> b1) {
							return new arrayTail(
								b1, 
								k);
						}
					});
			}
		}.APP(new F<Dmap<__t,__E>,F<DarrayTail<__t,__E>,Sigma>>() {
			public F<DarrayTail<__t,__E>,Sigma> APP(final Dmap<__t,__E> t1) {
				return new F<DarrayTail<__t,__E>,Sigma>() {
					public Sigma APP(final DarrayTail<__t,__E> t2) {
						return b.APP(new DarrayTailDcollection(
							t1, 
							t2));
					}
				};
			}
		});
	}
}
