/** Code generated by EriLex */
package databook.edsl.map;
public class DarrayTailEqAxiom {
	public <E,S,T> F<DarrayTail<S,E>,DarrayTail<T,E>> appl(
		final F<S,T> eq) {
		return ((F<DarrayTail<S,E>,DarrayTail<T,E>>) eq) ;
	}
	public <t,S,T> F<DarrayTail<t,T>,DarrayTail<t,T>> appr(
		final F<S,T> eq) {
		return ((F<DarrayTail<t,T>,DarrayTail<t,T>>) eq) ;
	}
}
