/** Code generated by EriLex */
package databook.edsl.map;
public class DarrayTailDend<__t,__E> extends DarrayTail<__t,__E> {
	public DarrayTailDend() {
		super(new erilex.tree.ASTValueData(
				"arrayTail", 
				"arrayTail")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"end", 
					"end")));
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DarrayTailDend<__t,__E> end() {
		return new DarrayTailDend<__t,__E>();
	}
}
