/** Code generated by EriLex */
package databook.edsl.map;
public class DarrayTailDattribute<__t,__E> extends DarrayTail<__t,__E> {
	java.lang.String i0;
	Dvalue<__t,__E> i1;
	Dunit<__t,__E> i2;
	DarrayTail<__t,__E> i3;
	public DarrayTailDattribute(
		final java.lang.String i0, 
		final Dvalue<__t,__E> i1, 
		final Dunit<__t,__E> i2, 
		final DarrayTail<__t,__E> i3) {
		super(new erilex.tree.ASTValueData(
				"arrayTail", 
				"arrayTail")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"attribute", 
					"attribute")), 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"nat", 
					null, 
					i0)), 
			i1, 
			i2, 
			i3);
		this.i0=i0;
		this.i1=i1;
		this.i2=i2;
		this.i3=i3;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DarrayTailDattribute<__t,__E> attribute(
		final java.lang.String i0, 
		final Dvalue<__t,__E> i1, 
		final Dunit<__t,__E> i2, 
		final DarrayTail<__t,__E> i3) {
		return new DarrayTailDattribute<__t,__E>(
			i0, 
			i1, 
			i2, 
			i3);
	}
}
