/** Code generated by EriLex */
package databook.edsl.map;
public class DarrayTailDobject<__t,__E> extends DarrayTail<__t,__E> {
	Dmap<__t,__E> i0;
	DarrayTail<__t,__E> i1;
	public DarrayTailDobject(
		final Dmap<__t,__E> i0, 
		final DarrayTail<__t,__E> i1) {
		super(new erilex.tree.ASTValueData(
				"arrayTail", 
				"arrayTail")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"object", 
					"object")), 
			i0, 
			i1);
		this.i0=i0;
		this.i1=i1;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DarrayTailDobject<__t,__E> object(
		final Dmap<__t,__E> i0, 
		final DarrayTail<__t,__E> i1) {
		return new DarrayTailDobject<__t,__E>(
			i0, 
			i1);
	}
}
