/** Code generated by EriLex */
package databook.edsl.map;
public class DarrayTailDelem<__t,__E,t> extends DarrayTail<__t,__E> {
	t i0;
	DarrayTail<__t,__E> i1;
	public DarrayTailDelem(
		final t i0, 
		final DarrayTail<__t,__E> i1) {
		super(new erilex.tree.ASTValueData(
				"arrayTail", 
				"arrayTail")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"elem", 
					"elem")), 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"nat", 
					null, 
					i0)), 
			i1);
		this.i0=i0;
		this.i1=i1;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E,t> DarrayTailDelem<__t,__E,t> elem(
		final t i0, 
		final DarrayTail<__t,__E> i1) {
		return new DarrayTailDelem<__t,__E,t>(
			i0, 
			i1);
	}
}
