/** Code generated by EriLex */
package databook.edsl.map;
public class Devaluate extends Visitor {
	public java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDattribute d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDelem d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDobject d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDdataObject d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDend d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDcollection d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DjsonDobject d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DjsonDmessages d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DjsonDmessage d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DlocDirods d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DlocDtripleStore d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DlocDend d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmapDdataObject d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmapDkey d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmapDat d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmapDend d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmapDcollection d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmapDhasPart d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmapDuri d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmapDlabel d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmapValueDvalue d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmapValueDarray d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDmodify d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDdelete d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDcreate d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDunion d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDdiff d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDend d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DunitDunit d) {
		return new Evaluators().evaluate(d, 
			key);
	}
	public java.lang.Object visit(
		final java.lang.String key, 
		final DvalueDvalue d) {
		return new Evaluators().evaluate(d, 
			key);
	}
}
