/** Code generated by EriLex */
package databook.edsl.map;
public class DjsonDmessages<__t,__E> extends Djson<__t,__E> {
	Dmsg<__t,__E> i0;
	public DjsonDmessages(
		final Dmsg<__t,__E> i0) {
		super(new erilex.tree.ASTValueData(
				"json", 
				"json")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"messages", 
					"messages")), 
			i0);
		this.i0=i0;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DjsonDmessages<__t,__E> messages(
		final Dmsg<__t,__E> i0) {
		return new DjsonDmessages<__t,__E>(
			i0);
	}
}
