/** Code generated by EriLex */
package databook.edsl.map;
public class DjsonDmessage<__t,__E> extends Djson<__t,__E> {
	Dmap<__t,__E> i0;
	public DjsonDmessage(
		final Dmap<__t,__E> i0) {
		super(new erilex.tree.ASTValueData(
				"json", 
				"json")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"message", 
					"message")), 
			i0);
		this.i0=i0;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DjsonDmessage<__t,__E> message(
		final Dmap<__t,__E> i0) {
		return new DjsonDmessage<__t,__E>(
			i0);
	}
}
