/** Code generated by EriLex */
package databook.edsl.map;
public class DlocDend<__t,__E> extends Dloc<__t,__E> {
	public DlocDend() {
		super(new erilex.tree.ASTValueData(
				"loc", 
				"loc")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"end", 
					"end")));
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DlocDend<__t,__E> end() {
		return new DlocDend<__t,__E>();
	}
}
