/** Code generated by EriLex */
package databook.edsl.map;
public class DlocEqAxiom {
	public <E,S,T> F<Dloc<S,E>,Dloc<T,E>> appl(
		final F<S,T> eq) {
		return ((F<Dloc<S,E>,Dloc<T,E>>) eq) ;
	}
	public <t,S,T> F<Dloc<t,T>,Dloc<t,T>> appr(
		final F<S,T> eq) {
		return ((F<Dloc<t,T>,Dloc<t,T>>) eq) ;
	}
}
