/** Code generated by EriLex */
package databook.edsl.map;
public class DmapDcollection<__t,__E> extends Dmap<__t,__E> {
	Dmap<__t,__E> i0;
	public DmapDcollection(
		final Dmap<__t,__E> i0) {
		super(new erilex.tree.ASTValueData(
				"map", 
				"map")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"collection", 
					"collection")), 
			i0);
		this.i0=i0;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DmapDcollection<__t,__E> collection(
		final Dmap<__t,__E> i0) {
		return new DmapDcollection<__t,__E>(
			i0);
	}
}
