/** Code generated by EriLex */
package databook.edsl.map;
public class DmapDlabel<__t,__E> extends Dmap<__t,__E> {
	java.lang.String i0;
	Dmap<__t,__E> i1;
	public DmapDlabel(
		final java.lang.String i0, 
		final Dmap<__t,__E> i1) {
		super(new erilex.tree.ASTValueData(
				"map", 
				"map")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"label", 
					"label")), 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"nat", 
					null, 
					i0)), 
			i1);
		this.i0=i0;
		this.i1=i1;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DmapDlabel<__t,__E> label(
		final java.lang.String i0, 
		final Dmap<__t,__E> i1) {
		return new DmapDlabel<__t,__E>(
			i0, 
			i1);
	}
}
