/** Code generated by EriLex */
package databook.edsl.map;
public class DmapDend<__t,__E> extends Dmap<__t,__E> {
	public DmapDend() {
		super(new erilex.tree.ASTValueData(
				"map", 
				"map")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"end", 
					"end")));
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DmapDend<__t,__E> end() {
		return new DmapDend<__t,__E>();
	}
}
