/** Code generated by EriLex */
package databook.edsl.map;
public class DmapDkey<__t,__E> extends Dmap<__t,__E> {
	java.lang.String i0;
	DmapValue<__t,__E> i1;
	public DmapDkey(
		final java.lang.String i0, 
		final DmapValue<__t,__E> i1) {
		super(new erilex.tree.ASTValueData(
				"map", 
				"map")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"key", 
					"key")), 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"nat", 
					null, 
					i0)), 
			i1);
		this.i0=i0;
		this.i1=i1;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DmapDkey<__t,__E> key(
		final java.lang.String i0, 
		final DmapValue<__t,__E> i1) {
		return new DmapDkey<__t,__E>(
			i0, 
			i1);
	}
}
