/** Code generated by EriLex */
package databook.edsl.map;
public class DmapValueDvalue<__t,__E,t> extends DmapValue<__t,__E> {
	t i0;
	Dmap<__t,__E> i1;
	public DmapValueDvalue(
		final t i0, 
		final Dmap<__t,__E> i1) {
		super(new erilex.tree.ASTValueData(
				"mapValue", 
				"mapValue")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"value", 
					"value")), 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"nat", 
					null, 
					i0)), 
			i1);
		this.i0=i0;
		this.i1=i1;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E,t> DmapValueDvalue<__t,__E,t> value(
		final t i0, 
		final Dmap<__t,__E> i1) {
		return new DmapValueDvalue<__t,__E,t>(
			i0, 
			i1);
	}
}
