/** Code generated by EriLex */
package databook.edsl.map;
public class DmapEqAxiom {
	public <E,S,T> F<Dmap<S,E>,Dmap<T,E>> appl(
		final F<S,T> eq) {
		return ((F<Dmap<S,E>,Dmap<T,E>>) eq) ;
	}
	public <t,S,T> F<Dmap<t,T>,Dmap<t,T>> appr(
		final F<S,T> eq) {
		return ((F<Dmap<t,T>,Dmap<t,T>>) eq) ;
	}
}
