/** Code generated by EriLex */
package databook.edsl.map;
public class DmapValueDarray<__t,__E> extends DmapValue<__t,__E> {
	DarrayTail<__t,__E> i0;
	Dmap<__t,__E> i1;
	public DmapValueDarray(
		final DarrayTail<__t,__E> i0, 
		final Dmap<__t,__E> i1) {
		super(new erilex.tree.ASTValueData(
				"mapValue", 
				"mapValue")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"array", 
					"array")), 
			i0, 
			i1);
		this.i0=i0;
		this.i1=i1;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DmapValueDarray<__t,__E> array(
		final DarrayTail<__t,__E> i0, 
		final Dmap<__t,__E> i1) {
		return new DmapValueDarray<__t,__E>(
			i0, 
			i1);
	}
}
