/** Code generated by EriLex */
package databook.edsl.map;
public class DmsgDdelete<__t,__E> extends Dmsg<__t,__E> {
	Dmap<__t,__E> i0;
	Dmsg<__t,__E> i1;
	public DmsgDdelete(
		final Dmap<__t,__E> i0, 
		final Dmsg<__t,__E> i1) {
		super(new erilex.tree.ASTValueData(
				"msg", 
				"msg")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"delete", 
					"delete")), 
			i0, 
			i1);
		this.i0=i0;
		this.i1=i1;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DmsgDdelete<__t,__E> delete(
		final Dmap<__t,__E> i0, 
		final Dmsg<__t,__E> i1) {
		return new DmsgDdelete<__t,__E>(
			i0, 
			i1);
	}
}
