/** Code generated by EriLex */
package databook.edsl.map;
public class DmsgDend<__t,__E> extends Dmsg<__t,__E> {
	public DmsgDend() {
		super(new erilex.tree.ASTValueData(
				"msg", 
				"msg")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"end", 
					"end")));
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DmsgDend<__t,__E> end() {
		return new DmsgDend<__t,__E>();
	}
}
