/** Code generated by EriLex */
package databook.edsl.map;
public class DmsgEqAxiom {
	public <E,S,T> F<Dmsg<S,E>,Dmsg<T,E>> appl(
		final F<S,T> eq) {
		return ((F<Dmsg<S,E>,Dmsg<T,E>>) eq) ;
	}
	public <t,S,T> F<Dmsg<t,T>,Dmsg<t,T>> appr(
		final F<S,T> eq) {
		return ((F<Dmsg<t,T>,Dmsg<t,T>>) eq) ;
	}
}
