/** Code generated by EriLex */
package databook.edsl.map;
public class DunitEqAxiom {
	public <E,S,T> F<Dunit<S,E>,Dunit<T,E>> appl(
		final F<S,T> eq) {
		return ((F<Dunit<S,E>,Dunit<T,E>>) eq) ;
	}
	public <t,S,T> F<Dunit<t,T>,Dunit<t,T>> appr(
		final F<S,T> eq) {
		return ((F<Dunit<t,T>,Dunit<t,T>>) eq) ;
	}
}
