/** Code generated by EriLex */
package databook.edsl.map;
public class DunitDunit<__t,__E> extends Dunit<__t,__E> {
	java.lang.String i0;
	public DunitDunit(
		final java.lang.String i0) {
		super(new erilex.tree.ASTValueData(
				"unit", 
				"unit")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"unit", 
					"unit")), 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"nat", 
					null, 
					i0)));
		this.i0=i0;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DunitDunit<__t,__E> unit(
		final java.lang.String i0) {
		return new DunitDunit<__t,__E>(
			i0);
	}
}
