/** Code generated by EriLex */
package databook.edsl.map;
public class DuriEqAxiom {
	public <E,S,T> F<Duri<S,E>,Duri<T,E>> appl(
		final F<S,T> eq) {
		return ((F<Duri<S,E>,Duri<T,E>>) eq) ;
	}
	public <t,S,T> F<Duri<t,T>,Duri<t,T>> appr(
		final F<S,T> eq) {
		return ((F<Duri<t,T>,Duri<t,T>>) eq) ;
	}
}
