/** Code generated by EriLex */
package databook.edsl.map;
public class DvalueDvalue<__t,__E> extends Dvalue<__t,__E> {
	java.lang.String i0;
	public DvalueDvalue(
		final java.lang.String i0) {
		super(new erilex.tree.ASTValueData(
				"value", 
				"value")
			, 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"value", 
					"value")), 
			new erilex.data.generic.Tree(
				new erilex.tree.ASTValueData(
					"nat", 
					null, 
					i0)));
		this.i0=i0;
	}
	public java.lang.Object accept(
		final Visitor v, 
		final java.lang.String key) {
		return v.visit(key, 
			this);
	}
	public static <__t,__E> DvalueDvalue<__t,__E> value(
		final java.lang.String i0) {
		return new DvalueDvalue<__t,__E>(
			i0);
	}
}
