/** Code generated by EriLex */
package databook.edsl.map;
public class DvalueEqAxiom {
	public <E,S,T> F<Dvalue<S,E>,Dvalue<T,E>> appl(
		final F<S,T> eq) {
		return ((F<Dvalue<S,E>,Dvalue<T,E>>) eq) ;
	}
	public <t,S,T> F<Dvalue<t,T>,Dvalue<t,T>> appr(
		final F<S,T> eq) {
		return ((F<Dvalue<t,T>,Dvalue<t,T>>) eq) ;
	}
}
