/** Code generated by EriLex */
package databook.edsl.map;
public class Evaluators {
	public java.lang.Object evaluate(
		final Object evaluate_param, 
		final java.lang.String key) {
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("end") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("arrayTail"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			{			
	return new java.util.LinkedList();			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("messages") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("json"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object msg=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			{			
	Object ms = evaluate(msg, null);			
	return 			
		Utils.prog().object()			
			.key("type").value("Messages")			
			.key("messages").value(ms)			
		.end().run();			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("label") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("map"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final java.lang.String l=(java.lang.String)NAT(((erilex.data.generic.Tree)evaluate_param).subtrees[1]);
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.Map m = (java.util.HashMap) evaluate(map, null);			
	m.put("label", l);			
	return m;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("modify") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("msg"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object map2=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			final Object msg=((erilex.data.generic.Tree)evaluate_param).subtrees[3];
			{			
	java.util.List l = (java.util.List) evaluate(msg, null);			
	Object o = evaluate(map, null);			
	Object o2 = evaluate(map2, null);			
	Object hm = 			
		Utils.prog().message()			
			.key("operation").value("modify")			
			.hasPart().elem(o).elem(o2).end()			
		.end().run();			
	l.add(0, hm);			
	return l;			
				
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("value") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("mapValue"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object v=(Object)NAT(((erilex.data.generic.Tree)evaluate_param).subtrees[1]);
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.Map m = (java.util.HashMap) evaluate(map, null);			
	m.put(key, v);			
	return m;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("hasPart") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("map"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object arrayTail=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.Map m = (java.util.HashMap) evaluate(map, null);			
	Object l = evaluate(arrayTail, null);			
	m.put("hasPart", l);			
	return m;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("attribute") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("arrayTail"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final java.lang.String s=(java.lang.String)NAT(((erilex.data.generic.Tree)evaluate_param).subtrees[1]);
			final Object value=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			final Object unit=((erilex.data.generic.Tree)evaluate_param).subtrees[3];
			final Object arrayTail=((erilex.data.generic.Tree)evaluate_param).subtrees[4];
			{			
	java.util.List l = (java.util.List) evaluate(arrayTail, null);			
	Object v = evaluate(value, null);			
	Object u = evaluate(unit, null);			
	Object hm = 			
		Utils.prog().object()			
			.key("type").value("AVU")			
			.key("attribute").value(s)			
			.key("value").value(v)			
			.key("unit").value(u)			
		.end().run();			
	l.add(0, hm);			
	return l;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("diff") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("msg"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object map2=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			final Object msg=((erilex.data.generic.Tree)evaluate_param).subtrees[3];
			{			
	java.util.List l = (java.util.List) evaluate(msg, null);			
	Object o = evaluate(map, null);			
	Object o2 = evaluate(map2, null);			
	Object hm = 			
		Utils.prog().message()			
			.key("operation").value("diff")			
			.hasPart().elem(o).elem(o2).end()			
		.end().run();			
	l.add(0, hm);			
	return l;			
				
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("union") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("msg"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object map2=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			final Object msg=((erilex.data.generic.Tree)evaluate_param).subtrees[3];
			{			
	java.util.List l = (java.util.List) evaluate(msg, null);			
	Object o = evaluate(map, null);			
	Object o2 = evaluate(map2, null);			
	Object hm = 			
		Utils.prog().message()			
			.key("operation").value("union")			
			.hasPart().elem(o).elem(o2).end()			
		.end().run();			
	l.add(0, hm);			
	return l;			
				
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("dataObject") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("map"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			{			
	java.util.Map m = (java.util.HashMap) evaluate(map, null);			
	m.put("type", "DataObject");			
	return m;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("key") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("map"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final java.lang.String k=(java.lang.String)NAT(((erilex.data.generic.Tree)evaluate_param).subtrees[1]);
			final Object mapValue=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	return evaluate(mapValue, k);			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("object") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("arrayTail"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object arrayTail=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	Object m = evaluate(map, null);			
	java.util.List l = (java.util.List) evaluate(arrayTail, null);			
	l.add(0, m);			
	return l;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("end") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("loc"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			{			
	return new java.util.LinkedList();			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("message") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("json"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			{			
	java.util.Map m = (java.util.HashMap) evaluate(map, null);			
	m.put("type", "Message");			
	return m;			
			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("end") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("msg"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			{			
	return new java.util.LinkedList();			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("collection") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("map"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			{			
	java.util.Map m = (java.util.HashMap) evaluate(map, null);			
	m.put("type", "Collection");			
	return m;			
			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("elem") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("arrayTail"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object v=(Object)NAT(((erilex.data.generic.Tree)evaluate_param).subtrees[1]);
			final Object arrayTail=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.List l = (java.util.List) evaluate(arrayTail, null);			
	l.add(0, v);			
	return l; 			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("at") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("map"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object loc=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.Map m = (java.util.HashMap) evaluate(map, null);			
	java.util.List l = (java.util.List) evaluate(loc, null);			
	m.put("storageLocationRequest", l);			
	return m;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("value") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("value"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final java.lang.String s=(java.lang.String)NAT(((erilex.data.generic.Tree)evaluate_param).subtrees[1]);
			{			
	return s;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("object") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("json"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			{			
	java.util.Map m = (java.util.Map) evaluate(map, null);			
	return m;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("dataObject") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("arrayTail"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object arrayTail=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.List l = (java.util.List) evaluate(arrayTail, null);			
	java.util.Map m = (java.util.HashMap) evaluate(map, null);			
	m.put("type", "DataObject");			
	l.add(0, m);			
	return l;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("create") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("msg"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object msg=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.List l = (java.util.List) evaluate(msg, null);			
	Object o = evaluate(map, null);			
	Object hm = 			
		Utils.prog().message()			
			.key("operation").value("create")			
			.hasPart().elem(o).end()			
		.end().run();			
	l.add(0, hm);			
	return l;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("unit") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("unit"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final java.lang.String s=(java.lang.String)NAT(((erilex.data.generic.Tree)evaluate_param).subtrees[1]);
			{			
	return s;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("array") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("mapValue"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object arrayTail=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.Map m = (java.util.Map) evaluate(map, null);			
	Object l = evaluate(arrayTail, null);			
	m.put(key, l);			
	return m;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("irods") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("loc"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object loc=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			{			
	java.util.List l = (java.util.List) evaluate(loc, null);			
	l.add(0, "irods");			
	return l;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("tripleStore") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("loc"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object loc=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			{			
	java.util.List l = (java.util.List) evaluate(loc, null);			
	l.add(0, "tripleStore");			
	return l;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("end") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("map"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			{			
	return new java.util.HashMap();			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("collection") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("arrayTail"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object arrayTail=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.List l = (java.util.List) evaluate(arrayTail, null);			
	java.util.Map m = (java.util.HashMap) evaluate(map, null);			
	m.put("type", "Collection");			
	l.add(0, m);			
	return l;			
			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("uri") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("map"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final java.lang.String u=(java.lang.String)NAT(((erilex.data.generic.Tree)evaluate_param).subtrees[1]);
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.Map m = (java.util.HashMap) evaluate(map, null);			
	m.put("uri", u);			
	return m;			
}
		}
		else 
		if(((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).subtrees[0].val).name.equals("delete") && ((erilex.tree.ASTValueData)((erilex.data.generic.Tree)evaluate_param).val).name.equals("msg"))
		{
			final Object __this__=((erilex.data.generic.Tree)evaluate_param).subtrees[0];
			final Object map=((erilex.data.generic.Tree)evaluate_param).subtrees[1];
			final Object msg=((erilex.data.generic.Tree)evaluate_param).subtrees[2];
			{			
	java.util.List l = (java.util.List) evaluate(msg, null);			
	Object o = evaluate(map, null);			
	Object hm = 			
		Utils.prog().message()			
			.key("operation").value("delete")			
			.hasPart().elem(o).end()			
		.end().run();			
	l.add(0, hm);			
	return l;			
			
}
		}
		else 
			return ((java.lang.Object) evaluate_param) ;
	}
	public java.lang.Object NAT(
		final java.lang.Object tree) {
		return ((erilex.tree.ASTValueData) ((erilex.data.generic.Tree) tree) .val) .obj;
	}
}
