/** Code generated by EriLex */
package databook.edsl.map;
public class json<Kappa,Sigma,__t,__E> {
	F<Djson<__t,__E>,Sigma> b;
	F<Sigma,Kappa> k;
	public json(
		final F<Djson<__t,__E>,Sigma> b, 
		final F<Sigma,Kappa> k) {
		this.b=b;
		this.k=k;
	}
	public map<Kappa,Sigma,__t,__E> object() {
		return new F<F<Dmap<__t,__E>,Sigma>,map<Kappa,Sigma,__t,__E>>() {
			public map<Kappa,Sigma,__t,__E> APP(final F<Dmap<__t,__E>,Sigma> b1) {
				return new map(
					b1, 
					k);
			}
		}.APP(new F<Dmap<__t,__E>,Sigma>() {
			public Sigma APP(final Dmap<__t,__E> t1) {
				return b.APP(new DjsonDobject(
					t1));
			}
		});
	}
	public msg<Kappa,Sigma,__t,__E> messages() {
		return new F<F<Dmsg<__t,__E>,Sigma>,msg<Kappa,Sigma,__t,__E>>() {
			public msg<Kappa,Sigma,__t,__E> APP(final F<Dmsg<__t,__E>,Sigma> b1) {
				return new msg(
					b1, 
					k);
			}
		}.APP(new F<Dmsg<__t,__E>,Sigma>() {
			public Sigma APP(final Dmsg<__t,__E> t1) {
				return b.APP(new DjsonDmessages(
					t1));
			}
		});
	}
	public map<Kappa,Sigma,__t,__E> message() {
		return new F<F<Dmap<__t,__E>,Sigma>,map<Kappa,Sigma,__t,__E>>() {
			public map<Kappa,Sigma,__t,__E> APP(final F<Dmap<__t,__E>,Sigma> b1) {
				return new map(
					b1, 
					k);
			}
		}.APP(new F<Dmap<__t,__E>,Sigma>() {
			public Sigma APP(final Dmap<__t,__E> t1) {
				return b.APP(new DjsonDmessage(
					t1));
			}
		});
	}
}
