/** Code generated by EriLex */
package databook.edsl.map;
public class loc<Kappa,Sigma,__t,__E> {
	F<Dloc<__t,__E>,Sigma> b;
	F<Sigma,Kappa> k;
	public loc(
		final F<Dloc<__t,__E>,Sigma> b, 
		final F<Sigma,Kappa> k) {
		this.b=b;
		this.k=k;
	}
	public loc<Kappa,Sigma,__t,__E> irods() {
		return new F<F<Dloc<__t,__E>,Sigma>,loc<Kappa,Sigma,__t,__E>>() {
			public loc<Kappa,Sigma,__t,__E> APP(final F<Dloc<__t,__E>,Sigma> b1) {
				return new loc(
					b1, 
					k);
			}
		}.APP(new F<Dloc<__t,__E>,Sigma>() {
			public Sigma APP(final Dloc<__t,__E> t1) {
				return b.APP(new DlocDirods(
					t1));
			}
		});
	}
	public loc<Kappa,Sigma,__t,__E> tripleStore() {
		return new F<F<Dloc<__t,__E>,Sigma>,loc<Kappa,Sigma,__t,__E>>() {
			public loc<Kappa,Sigma,__t,__E> APP(final F<Dloc<__t,__E>,Sigma> b1) {
				return new loc(
					b1, 
					k);
			}
		}.APP(new F<Dloc<__t,__E>,Sigma>() {
			public Sigma APP(final Dloc<__t,__E> t1) {
				return b.APP(new DlocDtripleStore(
					t1));
			}
		});
	}
	public Kappa end() {
		return k.APP(b.APP(new DlocDend()));
	}
}
