/** Code generated by EriLex */
package databook.edsl.map;
public class mapValue<Kappa,Sigma,__t,__E> {
	F<DmapValue<__t,__E>,Sigma> b;
	F<Sigma,Kappa> k;
	public mapValue(
		final F<DmapValue<__t,__E>,Sigma> b, 
		final F<Sigma,Kappa> k) {
		this.b=b;
		this.k=k;
	}
	public <t> map<Kappa,Sigma,__t,__E> value(
		final t i1) {
		return new F<F<Dmap<__t,__E>,Sigma>,map<Kappa,Sigma,__t,__E>>() {
			public map<Kappa,Sigma,__t,__E> APP(final F<Dmap<__t,__E>,Sigma> b1) {
				return new map(
					b1, 
					k);
			}
		}.APP(new F<Dmap<__t,__E>,Sigma>() {
			public Sigma APP(final Dmap<__t,__E> t1) {
				return b.APP(new DmapValueDvalue(
					i1, 
					t1));
			}
		});
	}
	public arrayTail<map<Kappa,Sigma,__t,__E>,F<Dmap<__t,__E>,Sigma>,__t,__E> array() {
		return new F<F<DarrayTail<__t,__E>,F<Dmap<__t,__E>,Sigma>>,arrayTail<map<Kappa,Sigma,__t,__E>,F<Dmap<__t,__E>,Sigma>,__t,__E>>() {
			public arrayTail<map<Kappa,Sigma,__t,__E>,F<Dmap<__t,__E>,Sigma>,__t,__E> APP(final F<DarrayTail<__t,__E>,F<Dmap<__t,__E>,Sigma>> b2) {
				return new arrayTail(
					b2, 
					new F<F<Dmap<__t,__E>,Sigma>,map<Kappa,Sigma,__t,__E>>() {
						public map<Kappa,Sigma,__t,__E> APP(final F<Dmap<__t,__E>,Sigma> b1) {
							return new map(
								b1, 
								k);
						}
					});
			}
		}.APP(new F<DarrayTail<__t,__E>,F<Dmap<__t,__E>,Sigma>>() {
			public F<Dmap<__t,__E>,Sigma> APP(final DarrayTail<__t,__E> t1) {
				return new F<Dmap<__t,__E>,Sigma>() {
					public Sigma APP(final Dmap<__t,__E> t2) {
						return b.APP(new DmapValueDarray(
							t1, 
							t2));
					}
				};
			}
		});
	}
}
