/** Code generated by EriLex */
package databook.edsl.map;
public class msg<Kappa,Sigma,__t,__E> {
	F<Dmsg<__t,__E>,Sigma> b;
	F<Sigma,Kappa> k;
	public msg(
		final F<Dmsg<__t,__E>,Sigma> b, 
		final F<Sigma,Kappa> k) {
		this.b=b;
		this.k=k;
	}
	public map<map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,__t,__E> modify() {
		return new F<F<Dmap<__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>>,map<map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,__t,__E>>() {
			public map<map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,__t,__E> APP(final F<Dmap<__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>> b3) {
				return new map(
					b3, 
					new F<F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>>() {
						public map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E> APP(final F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>> b2) {
							return new map(
								b2, 
								new F<F<Dmsg<__t,__E>,Sigma>,msg<Kappa,Sigma,__t,__E>>() {
									public msg<Kappa,Sigma,__t,__E> APP(final F<Dmsg<__t,__E>,Sigma> b1) {
										return new msg(
											b1, 
											k);
									}
								});
						}
					});
			}
		}.APP(new F<Dmap<__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>>() {
			public F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>> APP(final Dmap<__t,__E> t1) {
				return new F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>() {
					public F<Dmsg<__t,__E>,Sigma> APP(final Dmap<__t,__E> t2) {
						return new F<Dmsg<__t,__E>,Sigma>() {
							public Sigma APP(final Dmsg<__t,__E> t3) {
								return b.APP(new DmsgDmodify(
									t1, 
									t2, 
									t3));
							}
						};
					}
				};
			}
		});
	}
	public map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E> delete() {
		return new F<F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>>() {
			public map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E> APP(final F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>> b2) {
				return new map(
					b2, 
					new F<F<Dmsg<__t,__E>,Sigma>,msg<Kappa,Sigma,__t,__E>>() {
						public msg<Kappa,Sigma,__t,__E> APP(final F<Dmsg<__t,__E>,Sigma> b1) {
							return new msg(
								b1, 
								k);
						}
					});
			}
		}.APP(new F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>() {
			public F<Dmsg<__t,__E>,Sigma> APP(final Dmap<__t,__E> t1) {
				return new F<Dmsg<__t,__E>,Sigma>() {
					public Sigma APP(final Dmsg<__t,__E> t2) {
						return b.APP(new DmsgDdelete(
							t1, 
							t2));
					}
				};
			}
		});
	}
	public map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E> create() {
		return new F<F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>>() {
			public map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E> APP(final F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>> b2) {
				return new map(
					b2, 
					new F<F<Dmsg<__t,__E>,Sigma>,msg<Kappa,Sigma,__t,__E>>() {
						public msg<Kappa,Sigma,__t,__E> APP(final F<Dmsg<__t,__E>,Sigma> b1) {
							return new msg(
								b1, 
								k);
						}
					});
			}
		}.APP(new F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>() {
			public F<Dmsg<__t,__E>,Sigma> APP(final Dmap<__t,__E> t1) {
				return new F<Dmsg<__t,__E>,Sigma>() {
					public Sigma APP(final Dmsg<__t,__E> t2) {
						return b.APP(new DmsgDcreate(
							t1, 
							t2));
					}
				};
			}
		});
	}
	public map<map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,__t,__E> union() {
		return new F<F<Dmap<__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>>,map<map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,__t,__E>>() {
			public map<map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,__t,__E> APP(final F<Dmap<__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>> b3) {
				return new map(
					b3, 
					new F<F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>>() {
						public map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E> APP(final F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>> b2) {
							return new map(
								b2, 
								new F<F<Dmsg<__t,__E>,Sigma>,msg<Kappa,Sigma,__t,__E>>() {
									public msg<Kappa,Sigma,__t,__E> APP(final F<Dmsg<__t,__E>,Sigma> b1) {
										return new msg(
											b1, 
											k);
									}
								});
						}
					});
			}
		}.APP(new F<Dmap<__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>>() {
			public F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>> APP(final Dmap<__t,__E> t1) {
				return new F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>() {
					public F<Dmsg<__t,__E>,Sigma> APP(final Dmap<__t,__E> t2) {
						return new F<Dmsg<__t,__E>,Sigma>() {
							public Sigma APP(final Dmsg<__t,__E> t3) {
								return b.APP(new DmsgDunion(
									t1, 
									t2, 
									t3));
							}
						};
					}
				};
			}
		});
	}
	public map<map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,__t,__E> diff() {
		return new F<F<Dmap<__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>>,map<map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,__t,__E>>() {
			public map<map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,__t,__E> APP(final F<Dmap<__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>> b3) {
				return new map(
					b3, 
					new F<F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>,map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E>>() {
						public map<msg<Kappa,Sigma,__t,__E>,F<Dmsg<__t,__E>,Sigma>,__t,__E> APP(final F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>> b2) {
							return new map(
								b2, 
								new F<F<Dmsg<__t,__E>,Sigma>,msg<Kappa,Sigma,__t,__E>>() {
									public msg<Kappa,Sigma,__t,__E> APP(final F<Dmsg<__t,__E>,Sigma> b1) {
										return new msg(
											b1, 
											k);
									}
								});
						}
					});
			}
		}.APP(new F<Dmap<__t,__E>,F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>>() {
			public F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>> APP(final Dmap<__t,__E> t1) {
				return new F<Dmap<__t,__E>,F<Dmsg<__t,__E>,Sigma>>() {
					public F<Dmsg<__t,__E>,Sigma> APP(final Dmap<__t,__E> t2) {
						return new F<Dmsg<__t,__E>,Sigma>() {
							public Sigma APP(final Dmsg<__t,__E> t3) {
								return b.APP(new DmsgDdiff(
									t1, 
									t2, 
									t3));
							}
						};
					}
				};
			}
		});
	}
	public Kappa end() {
		return k.APP(b.APP(new DmsgDend()));
	}
}
