/** Code generated by EriLex */
package databook.edsl.map;
public class unit<Kappa,Sigma,__t,__E> {
	F<Dunit<__t,__E>,Sigma> b;
	F<Sigma,Kappa> k;
	public unit(
		final F<Dunit<__t,__E>,Sigma> b, 
		final F<Sigma,Kappa> k) {
		this.b=b;
		this.k=k;
	}
	public Kappa unit(
		final java.lang.String i1) {
		return k.APP(b.APP(new DunitDunit(
			i1)));
	}
}
