/** Code generated by EriLex */
package databook.edsl.map;
public class Utils {
	public static <T,__E> json<Djson<T,__E>,Djson<T,__E>,T,__E> json() {
		return new json<Djson<T,__E>,Djson<T,__E>,T,__E>(
			new UtilsST(), 
			new UtilsST());
	}
	public static <T,__E> json<Djson<T,__E>,Djson<T,__E>,T,__E> prog() {
		return json();
	}
	public static class UtilsST<T,__E> extends F<Djson<T,__E>,Djson<T,__E>> {
		public Djson<T,__E> APP(
			final Djson<T,__E> x) {
			return x;
		}
	}
}
