/** Code generated by EriLex */
package databook.edsl.map;
public class value<Kappa,Sigma,__t,__E> {
	F<Dvalue<__t,__E>,Sigma> b;
	F<Sigma,Kappa> k;
	public value(
		final F<Dvalue<__t,__E>,Sigma> b, 
		final F<Sigma,Kappa> k) {
		this.b=b;
		this.k=k;
	}
	public Kappa value(
		final java.lang.String i1) {
		return k.APP(b.APP(new DvalueDvalue(
			i1)));
	}
}
