/** Code generated by EriLex */
package databook.edsl.map;
public abstract class Visitor {
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDattribute d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDelem d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDobject d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDdataObject d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDend d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DarrayTailDcollection d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DjsonDobject d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DjsonDmessages d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DjsonDmessage d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DlocDirods d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DlocDtripleStore d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DlocDend d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmapDdataObject d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmapDkey d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmapDat d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmapDend d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmapDcollection d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmapDhasPart d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmapDuri d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmapDlabel d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmapValueDvalue d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmapValueDarray d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDmodify d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDdelete d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDcreate d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDunion d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDdiff d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DmsgDend d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DunitDunit d);
	public abstract java.lang.Object visit(
		final java.lang.String key, 
		final DvalueDvalue d);
}
